config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :inspirations, only: [:index, :create, :destroy] do
        get :search, on: :collection
      end
      resources :users, only: [:create] do
        get :current, on: :collection
      end
      resource :session, only: [:create, :destroy]
    end
  end

  get('/', {to: 'home#index', as: 'home'}) 
  match "*unmatched_route", via: :all, to: "home#index"

end

app/views/welcome/index.html.erb
<%= form_tag(home_path, :method => "get") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query, params[:query]) %>
  <%= submit_tag("Search", name: nil) %>
<% end %>

<ul>
    <% @mixed= @everything.shuffle %>
    <% @mixed.each do |key, value| %>
      <li>
        <% if key["title"] %>
          <%=link_to(key["title"], key["url"]) %><br />
          <%= link_to(image_tag(key["imageUrl"]), key["url"]) %><br />
          <% if key["hex"] %>
            #<%= key["hex"] %>
            <br />
            <%= link_to "Save", user_inspirations_path(current_user, title: key["title"], image_url: URI.encode(key["imageUrl"]), url: URI.encode(key["url"]), hex: key["hex"]), method: :post %>
          <% else %>
            <% hexArray = key["colors"] && key["colors"]["hex"] %>
            <% hexArray&.each do |hex| %>
              #<%= hex %>
            <% end %>
            <br />
            <%= link_to "Save", user_inspirations_path(current_user, title: key["title"], image_url: URI.encode(key["imageUrl"]), url: URI.encode(key["url"]), hex: hexArray), method: :post %>
          <% end %>
        <% else %>
          <% if key["description"] %>
            <%= link_to(key["description"], key["links"]["html"]) %><br />
          <% else %>
            <%= link_to("Untitled", key["links"]["html"])%><br />
          <% end %>
          <%= key["color"] %><br />
          <%= link_to(image_tag(key["urls"]["thumb"]), key["links"]["html"]) %><br />
          <% if key["description"] %>
            <%= link_to "Save", user_inspirations_path(current_user, title: key["description"], image_url: URI.encode(key["urls"]["thumb"]), url: URI.encode(key["links"]["html"]), hex: key["color"]), method: :post %>
          <% else %>
            <%= link_to "Save", user_inspirations_path(current_user, title: "Untitled", image_url: URI.encode(key["urls"]["thumb"]), url: URI.encode(key["links"]["html"]), hex: key["color"]), method: :post %>
          <% end %>
        <% end %>
      </li>
    <% end %>
</ul>